// examples/svelte/large-form/src/components/subscribe-button.svelte
<script lang="ts">
  import { useFormContext } from '../runes/form-context.js'

  const form = useFormContext()

  const { label }: { label: string } = $props()
</script>

<form.Subscribe selector={(state) => state.isSubmitting}>
  {#snippet children(isSubmitting)}
    <button type="submit" disabled={isSubmitting}>{label}</button>
  {/snippet}
</form.Subscribe>

// examples/vue/large-form/src/components/SubscribeButton.vue
<script setup lang="ts">
import { useFormContext } from '../hooks/form.ts'

defineProps<{ label: string }>()

const form = useFormContext()
</script>

<template>
  <form.Subscribe
    :selector="(state) => state.isSubmitting"
    v-slot="isSubmitting"
  >
    <button type="submit" :disabled="isSubmitting">{{ label }}</button>
  </form.Subscribe>
</template>
