// examples/lit/large-form/src/emergency-contact.ts
import { html } from 'lit'
import { textField } from './text-field'
import type { LitFormType } from '@tanstack/lit-form'
import type { peopleFormOptions } from './shared-form'

export function emergencyContactFields(
  form: LitFormType<typeof peopleFormOptions>,
) {
  return html`
    <section>
      <h2>Emergency Contact</h2>
      ${form.field({ name: 'emergencyContact.fullName' }, (field) =>
        textField(field, 'Full Name'),
      )}
      ${form.field({ name: 'emergencyContact.phone' }, (field) =>
        textField(field, 'Phone'),
      )}
    </section>
  `
}

// examples/angular/large-form/src/app/features/people/emergency-contact.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import {
  TanStackAppField,
  TanStackField,
  injectWithForm,
} from '@tanstack/angular-form'
import { TextField } from '../../components/text-field.component'
import { peopleFormOpts } from './shared-form'

@Component({
  selector: 'app-emergency-contact',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [TanStackField, TanStackAppField, TextField],
  template: `
    <app-text-field
      label="Full Name"
      tanstack-app-field
      [tanstackField]="withForm.form"
      name="emergencyContact.fullName"
    />
    <app-text-field
      label="Phone"
      tanstack-app-field
      [tanstackField]="withForm.form"
      name="emergencyContact.phone"
    />
  `,
})
export class EmergencyContact {
  withForm = injectWithForm({ ...peopleFormOpts })
}
