// examples/solid/basic-splitting-form/src/index.tsx
import { render } from 'solid-js/web'
import { createForm } from '@tanstack/solid-form'
import { FormSection } from './FormSection'
import { FormSubmitButton } from './FormSubmitButton'
import { StringField } from './StringField'
import { sharedFormOptions } from './sharedForm'
import './index.css'

function App() {
  const form = createForm(() => ({
    ...sharedFormOptions,
    onSubmit: ({ value }) => {
      console.log(value)
    },
  }))

  return (
    <div>
      <h1>Form Splitting Example</h1>
      <form
        onSubmit={(event) => {
          event.preventDefault()
          event.stopPropagation()
          form.handleSubmit()
        }}
      >
        <form.Field name="firstName">
          {(field) => <StringField field={field} label="First Name" />}
        </form.Field>
        <form.Field name="lastName">
          {(field) => <StringField field={field} label="Last Name" />}
        </form.Field>

        <FormSection form={form} />

        <FormSubmitButton form={form} />
        <button
          type="reset"
          onClick={(event) => {
            event.preventDefault()
            form.reset()
          }}
        >
          Reset
        </button>
      </form>
    </div>
  )
}

render(() => <App />, document.getElementById('root')!)

// examples/react/form-composition/src/index.tsx
import { useForm } from '@tanstack/react-form'
import ReactDOM from 'react-dom/client'
import './index.css'
import { StringField } from './StringField'
import { sharedFormOptions } from './sharedForm'
import { FormSection } from './FormSection'
import { FormSubmitButton } from './FormSubmitButton'
import { useAppForm } from './appForm/createFormHook'

function App() {
  const form = useAppForm({
    ...sharedFormOptions,
    onSubmit: ({ value }) => {
      // Do something with form data
      console.log(value)
    },
  })

  return (
    <div>
      <h1>Simple Form Example</h1>
      <form
        onSubmit={(e) => {
          e.preventDefault()
          e.stopPropagation()
          form.handleSubmit()
        }}
      >
        <form.Field name="firstName">
          {(field) => (
            <>
              <field.Text />
              <field.Number />
              <field.SelectMenu field={field} options={['Anything', 'Goes']} />
              <field.Error />
            </>
          )}
        </form.Field>
        <form.Field name="age">
          {(field) => (
            <>
              <field.Text />
              <field.Number />
              <field.SelectMenu field={field} options={['Anything', 'Goes']} />
              <field.Error />
            </>
          )}
        </form.Field>
        <form.Field name="fooOrBar">
          {(field) => (
            <>
              <field.Text />
              <field.Number />
              <field.SelectMenu field={field} options={['Anything', 'Goes']} />
              <field.SelectMenu field={field} options={['foo', 'bar']} />
              <field.Error />
            </>
          )}
        </form.Field>
        <FormSection form={form} />

        <FormSubmitButton form={form} />
        <button
          type="reset"
          onClick={(e) => {
            // Avoid unexpected resets of form elements (especially <select> elements)
            e.preventDefault()
            form.reset()
          }}
        >
          Reset
        </button>
      </form>
    </div>
  )
}

ReactDOM.createRoot(document.getElementById('root')!).render(<App />)
