// examples/solid/multi-step-wizard/src/features/wizard/step2-subform.tsx
import { step2Schema, stepValidator } from './shared-form'
import type { SolidFormType } from '@tanstack/solid-form'
import type { wizardFormOpts } from './shared-form'

type WizardForm = SolidFormType<typeof wizardFormOpts>

interface Step2FormProps {
  form: WizardForm
  step: number
  setStep: (step: number) => void
}

export function Step2Form(props: Step2FormProps) {
  return (
    <props.form.FormGroup
      name="step2"
      validators={[stepValidator(step2Schema)]}
      onSubmit={() => {
        props.form.handleSubmit()
      }}
    >
      {(formGroup) => (
        <form
          onSubmit={(event) => {
            event.preventDefault()
            event.stopPropagation()
            formGroup().handleSubmit()
          }}
        >
          <formGroup.Field name="name">
            {(field) => <field.TextField label="Step 2 Name" />}
          </formGroup.Field>
          <button type="button" onClick={() => props.setStep(props.step - 1)}>
            Back
          </button>
          <props.form.SubscribeButton label="Submit" />
        </form>
      )}
    </props.form.FormGroup>
  )
}

// examples/lit/multi-step-wizard/src/features/wizard/step2-subform.ts
import { LitElement, html } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import { TanStackStoreSelector } from '@tanstack/lit-store'
import { getFormType } from '@tanstack/lit-form'
import { wizardFormOpts, step2Schema } from './shared-form.js'
import '../../components/text-field.js'

const formType = getFormType(wizardFormOpts)

@customElement('step2-form')
export class Step2Form extends LitElement {
  @property({ attribute: false })
  form!: typeof formType

  @property({ type: Number })
  step = 1

  @property({ attribute: false })
  setStep: (step: number) => void = () => {}

  _selector = new TanStackStoreSelector(this, () => this.form?.api.store)

  protected createRenderRoot() {
    return this
  }

  render() {
    return this.form.group(
      {
        name: 'step2',
        validators: {
          onDynamic: step2Schema,
        },
        onGroupSubmit: () => {
          this.form.api.handleSubmit()
        },
      },
      (formGroup) => html`
        <form
          @submit=${(e: Event) => {
            e.preventDefault()
            e.stopPropagation()
            formGroup.handleSubmit()
          }}
        >
          ${this.form.field(
            { name: 'step2.name' },
            (field) =>
              html`<text-field
                label="Step 2 Name"
                .field=${field}
              ></text-field>`,
          )}

          <button type="button" @click=${() => this.setStep(this.step - 1)}>
            Back
          </button>
          <button type="submit">Submit</button>
        </form>
      `,
    )
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'step2-form': Step2Form
  }
}
