// examples/lit/basic-splitting-form/src/field-error.ts
import { html, nothing } from 'lit'
import type { AnyFieldApi } from '@tanstack/lit-form'

export function fieldError(field: AnyFieldApi) {
  return html`<small
    role=${field.meta.isInvalid ? 'alert' : nothing}
    aria-live="polite"
    >${field.errors.map((error) => error.message).join('\n')}</small
  >`
}

// examples/react/form-composition/src/appForm/FieldError.tsx
import { fieldComponent } from './createContexts'
import type { AnyFieldApi } from '@tanstack/react-form'

interface FieldInfoProps {
  field: AnyFieldApi
}

function FieldError({ field }: FieldInfoProps) {
  return (
    <small role={field.meta.isInvalid ? 'alert' : undefined} aria-live="polite">
      {field.errors.map((e) => e.message).join('\n')}
    </small>
  )
}

export const AppFormFieldError = fieldComponent.loose(FieldError, 'field')
