// examples/svelte/multi-step-wizard/src/features/wizard/Step1Form.svelte
<script lang="ts">
  import type { SvelteFormType } from '@tanstack/svelte-form'
  import { step1Schema, stepValidator } from './shared-form.js'
  import type { wizardFormOpts } from './shared-form.js'

  interface Props {
    form: SvelteFormType<typeof wizardFormOpts>
    step: number
    setStep: (step: number) => void
  }

  const { form, step, setStep }: Props = $props()
</script>

<form.FormGroup
  name="step1"
  validators={[stepValidator(step1Schema)]}
  onSubmit={() => setStep(step + 1)}
  onSubmitInvalid={() => {
    // Keep the user on this step when its scoped validation fails.
  }}
>
  {#snippet children(formGroup)}
    <form
      onsubmit={(event) => {
        event.preventDefault()
        event.stopPropagation()
        formGroup.handleSubmit()
      }}
    >
      <formGroup.Field name="name">
        {#snippet children(field)}
          <field.TextField label="Step 1 Name" />
        {/snippet}
      </formGroup.Field>
      <form.SubscribeButton label="Next" />
    </form>
  {/snippet}
</form.FormGroup>

// examples/vue/multi-step-wizard/src/features/wizard/Step1Form.vue
<script setup lang="ts">
import { computed } from 'vue'
import { step1Schema, stepValidator } from './shared-form.ts'
import type { VueFormType } from '@tanstack/vue-form'
import type { wizardFormOpts } from './shared-form.ts'

const props = defineProps<{
  form: VueFormType<typeof wizardFormOpts>
  step: number
  setStep: (step: number) => void
}>()

const form = computed(() => props.form)
</script>

<template>
  <form.FormGroup
    name="step1"
    :validators="[stepValidator(step1Schema)]"
    :on-submit="() => setStep(step + 1)"
    :on-submit-invalid="() => undefined"
    v-slot="{ group }"
  >
    <form @submit.prevent.stop="group.handleSubmit()">
      <group.Field name="name" v-slot="{ field }">
        <field.TextField label="Step 1 Name" />
      </group.Field>

      <form.SubscribeButton label="Next" />
    </form>
  </form.FormGroup>
</template>
