// packages/solid-form/src/formApiTypes.public.ts
import type { AnyFormApi, FormApi, FormErrorTypes } from '@tanstack/form-core'
import type { Component } from 'solid-js'
import type { SolidTanStackFormComponents } from './Components.public'
import type {
  AnySolidFormComponentMap,
  DefaultSolidFormComponentMap,
} from './AppForm/componentMap.public'

type ExtendedFormApi<
  TFormData,
  TFormErrorTypes extends FormErrorTypes,
  TFieldComponents extends Record<string, Component<any>>,
> = FormApi<TFormData, TFormErrorTypes> &
  SolidTanStackFormComponents<TFormData, TFormErrorTypes, TFieldComponents>

export type SolidFormApi<
  TFormData,
  TFormErrorTypes extends FormErrorTypes,
  TComponents extends AnySolidFormComponentMap = DefaultSolidFormComponentMap,
> = unknown extends TComponents['formComponents']
  ? ExtendedFormApi<TFormData, TFormErrorTypes, TComponents['fieldComponents']>
  : ExtendedFormApi<
      TFormData,
      TFormErrorTypes,
      TComponents['fieldComponents']
    > &
      TComponents['formComponents']

export type AnySolidFormApi = AnyFormApi &
  SolidTanStackFormComponents<any, any, any>

export type { SolidFormComponentMap } from './AppForm/componentMap.public'

// packages/react-form/src/ReactForm/formApiTypes.public.ts
import type {
  AnyFormApi,
  FormApi,
  FormValidatorMetas,
} from '@tanstack/form-core'
import type { FunctionComponent } from 'react'
import type { ReactTanStackFormComponents } from './Components.public'
import type { AnyReactFormComponentMap } from '../AppForm/componentMap.public'

type ExtendedFormApi<
  TFormData,
  TFormValidatorMetas extends FormValidatorMetas,
  TSubmitReturn,
  TFieldComponents extends Record<string, FunctionComponent<any>>,
> = FormApi<TFormData, TFormValidatorMetas, TSubmitReturn> &
  ReactTanStackFormComponents<
    TFormData,
    TFormValidatorMetas,
    TSubmitReturn,
    TFieldComponents
  >

export type ReactFormApi<
  TFormData,
  TFormValidatorMetas extends FormValidatorMetas,
  TSubmitReturn,
  TComponents extends AnyReactFormComponentMap,
> = unknown extends TComponents['formComponents']
  ? ExtendedFormApi<
      TFormData,
      TFormValidatorMetas,
      TSubmitReturn,
      TComponents['fieldComponents']
    >
  : ExtendedFormApi<
      TFormData,
      TFormValidatorMetas,
      TSubmitReturn,
      TComponents['fieldComponents']
    > &
      TComponents['formComponents']

export type AnyReactFormApi = AnyFormApi &
  ReactTanStackFormComponents<any, any, any, any>

export type { ReactFormComponentMap } from '../AppForm/componentMap.public'
