// packages/solid-form/src/AppForm/componentMap.public.ts
import type { Component } from 'solid-js'

export interface SolidFormComponentMap<
  TFormComponents extends Record<string, Component<any>>,
  TFieldComponents extends Record<string, Component<any>>,
> {
  formComponents: TFormComponents
  fieldComponents: TFieldComponents
}

export type AnySolidFormComponentMap = SolidFormComponentMap<
  Record<string, Component<any>>,
  Record<string, Component<any>>
>

export type DefaultSolidFormComponentMap = SolidFormComponentMap<
  Record<never, never>,
  Record<never, never>
>

// packages/react-form/src/AppForm/componentMap.public.ts
import type { FunctionComponent } from 'react'

export interface ReactFormComponentMap<
  TFormComponents extends Record<string, FunctionComponent<any>>,
  TFieldComponents extends Record<string, FunctionComponent<any>>,
> {
  formComponents: TFormComponents
  fieldComponents: TFieldComponents
}

export type AnyReactFormComponentMap = ReactFormComponentMap<
  Record<string, FunctionComponent<any>>,
  Record<string, FunctionComponent<any>>
>

export type DefaultReactFormComponentMap = ReactFormComponentMap<
  Record<never, never>,
  Record<never, never>
>
