// packages/solid-form/src/AppForm/fieldComponentHelpers.lib.ts
import { createComponent } from 'solid-js'
import { useFieldContext } from './contexts.lib'
import type { Component } from 'solid-js'

type AnyFieldComponent = Component<any>

export function wrapField(
  Component: AnyFieldComponent,
  fieldPropKey: string,
): AnyFieldComponent {
  return function TanStackFormFieldWrapper(props) {
    return createComponent(Component, {
      ...props,
      [fieldPropKey]: useFieldContext(),
    })
  }
}

export function brandComponentFactory(): (
  component: AnyFieldComponent,
) => AnyFieldComponent {
  return (component) => component
}

// packages/react-form/src/AppForm/fieldComponentHelpers.lib.tsx
import React from 'react'
import { useFieldContext } from './contexts.lib'
import type { FunctionComponent } from 'react'

type AnyFieldComponent = (props: any) => React.ReactNode

export function wrapField(
  Component: AnyFieldComponent,
  fieldPropKey: string,
): AnyFieldComponent {
  const Wrapper: FunctionComponent<any> = function TanStackFormFieldWrapper(
    props,
  ) {
    const field = useFieldContext()

    const newProps = { ...props, [fieldPropKey]: field }

    return <Component {...newProps} />
  }

  Wrapper.displayName = 'TanStackForm.FieldComponent'

  return Wrapper as never
}

export function brandComponentFactory(): (
  component: AnyFieldComponent,
) => AnyFieldComponent {
  return (component) => component
}
