// examples/vue/multi-step-wizard/src/components/TextField.vue
<script setup lang="ts">
import type { FieldWithValue } from '@tanstack/vue-form'

defineProps<{
  field: FieldWithValue<string>
  label: string
}>()
</script>

<template>
  <div>
    <label :for="field.name">{{ label }}</label>
    <input
      :id="field.name"
      :name="field.name"
      :value="field.value"
      :aria-invalid="field.meta.isInvalid"
      @input="field.handleChange(($event.target as HTMLInputElement).value)"
      @blur="field.handleBlur"
    />
    <div
      v-for="error in field.errors"
      :key="error.message"
      role="alert"
      style="color: red"
    >
      {{ error.message }}
    </div>
  </div>
</template>

// examples/lit/multi-step-wizard/src/text-field.ts
import { html } from 'lit'
import type { FieldWithValue } from '@tanstack/lit-form'

export function textField(field: FieldWithValue<string>, label: string) {
  return html`
    <label>
      <span>${label}</span>
      <input
        name=${field.name}
        .value=${field.value}
        @input=${(event: InputEvent) =>
          field.handleChange((event.currentTarget as HTMLInputElement).value)}
        @blur=${() => field.handleBlur()}
        aria-invalid=${field.meta.isInvalid ? 'true' : 'false'}
      />
      ${field.errors.map(
        (error) => html`<small role="alert">${error.message}</small>`,
      )}
    </label>
  `
}
