// examples/svelte/large-form/src/features/people/AddressFields.svelte
<script lang="ts">
  import type { SvelteFormType } from '@tanstack/svelte-form'
  import type { peopleFormOpts } from './shared-form.js'

  const { form }: { form: SvelteFormType<typeof peopleFormOpts> } = $props()
</script>

<section>
  <h2>Address</h2>
  <form.Field name="address.line1">
    {#snippet children(field)}<field.TextField label="Address Line 1" />{/snippet}
  </form.Field>
  <form.Field name="address.line2">
    {#snippet children(field)}<field.TextField label="Address Line 2" />{/snippet}
  </form.Field>
  <form.Field name="address.city">
    {#snippet children(field)}<field.TextField label="City" />{/snippet}
  </form.Field>
  <form.Field name="address.state">
    {#snippet children(field)}<field.TextField label="State" />{/snippet}
  </form.Field>
  <form.Field name="address.zip">
    {#snippet children(field)}<field.TextField label="ZIP Code" />{/snippet}
  </form.Field>
</section>

// examples/react/large-form/src/features/people/address-fields.tsx
import { peopleFormOpts } from './shared-form.tsx'
import type { ReactFormType } from '@tanstack/react-form'

interface AddressFieldsProps {
  form: ReactFormType<typeof peopleFormOpts>
}

export function AddressFields({ form }: AddressFieldsProps) {
  return (
    <div>
      <h2>Address</h2>
      <form.Field
        name="address.line1"
        children={(field) => <field.TextField label="Address Line 1" />}
      />
      <form.Field
        name="address.line2"
        children={(field) => <field.TextField label="Address Line 2" />}
      />
      <form.Field
        name="address.city"
        children={(field) => <field.TextField label="City" />}
      />
      <form.Field
        name="address.state"
        children={(field) => <field.TextField label="State" />}
      />
      <form.Field
        name="address.zip"
        children={(field) => <field.TextField label="ZIP Code" />}
      />
    </div>
  )
}
