// examples/vue/multi-step-wizard/src/components/TextField.vue
<script setup lang="ts">
import type { FieldWithValue } from '@tanstack/vue-form'

defineProps<{
  field: FieldWithValue<string>
  label: string
}>()
</script>

<template>
  <div>
    <label :for="field.name">{{ label }}</label>
    <input
      :id="field.name"
      :name="field.name"
      :value="field.value"
      :aria-invalid="field.meta.isInvalid"
      @input="field.handleChange(($event.target as HTMLInputElement).value)"
      @blur="field.handleBlur"
    />
    <div
      v-for="error in field.errors"
      :key="error.message"
      role="alert"
      style="color: red"
    >
      {{ error.message }}
    </div>
  </div>
</template>

// examples/svelte/multi-step-wizard/src/components/TextField.svelte
<script lang="ts">
  import type { FieldWithValue } from '@tanstack/svelte-form'

  interface Props {
    field: FieldWithValue<string>
    label: string
  }

  const { field, label }: Props = $props()
</script>

<div>
  <label>
    <span>{label}</span>
    <input
      name={field.name}
      value={field.value}
      oninput={(event) => field.handleChange(event.currentTarget.value)}
      onblur={field.handleBlur}
      aria-invalid={field.meta.isInvalid}
    />
  </label>
  {#each field.errors as error}
    <div role="alert" style="color: red">{error.message}</div>
  {/each}
</div>
