// examples/lit/basic-splitting-form/src/form-section.ts
import { html } from 'lit'
import { stringField } from './string-field'
import type { LitFormType } from '@tanstack/lit-form'
import type { sharedFormOptions } from './shared-form'

export function formSection(form: LitFormType<typeof sharedFormOptions>) {
  return html`
    ${form.field({ name: 'address.street' }, (field) =>
      stringField(field, 'Street'),
    )}
    ${form.field({ name: 'address.country' }, (field) =>
      stringField(field, 'Country'),
    )}
  `
}

// examples/preact/basic-splitting-form/src/FormSection.tsx
import { StringField } from './StringField'
import type { PreactFormType } from '@tanstack/preact-form'
import type { sharedFormOptions } from './sharedForm'

interface FormSectionProps {
  form: PreactFormType<typeof sharedFormOptions>
}

export function FormSection(props: FormSectionProps) {
  const { form } = props

  return (
    <>
      <form.Field name="address.street">
        {(field) => <StringField field={field} />}
      </form.Field>
      <form.Field name="address.country">
        {(field) => <StringField field={field} />}
      </form.Field>
    </>
  )
}
