// examples/solid/basic-splitting-form/src/StringField.tsx
import { FieldError } from './FieldError'
import type { Accessor } from 'solid-js'
import type { FieldWithValue } from '@tanstack/solid-form'

interface StringFieldProps {
  field: Accessor<FieldWithValue<string>>
  label: string
}

export function StringField(props: StringFieldProps) {
  return (
    <label classList={{ validating: props.field().meta.isValidating }}>
      <span>{props.label}</span>
      <input
        name={props.field().name}
        value={props.field().value}
        onBlur={props.field().handleBlur}
        onInput={(event) =>
          props.field().handleChange(event.currentTarget.value)
        }
        aria-invalid={props.field().meta.isInvalid}
      />
      <FieldError field={props.field} />
    </label>
  )
}

// examples/preact/basic-splitting-form/src/StringField.tsx
import { FieldError } from './FieldError'
import type { FieldWithValue } from '@tanstack/preact-form'

interface StringFieldProps {
  field: FieldWithValue<string>
}

export function StringField(props: StringFieldProps) {
  const { field } = props

  return (
    <label className={field.meta.isValidating ? 'validating' : ''}>
      <span>First Name</span>

      <input
        name={field.name}
        value={field.value}
        onBlur={field.handleBlur}
        onInput={(e) => field.handleChange(e.currentTarget.value)}
        aria-invalid={field.meta.isInvalid}
      />
      <FieldError field={field} />
    </label>
  )
}
