// packages/react-form/src/FieldGroup/FieldGroupApi.public.ts
import type {
  DeepKeys,
  DeepKeysWhereValueIncludes,
  DeepValue,
  FieldValidators,
  FormApiArrayMethods,
  FormApiFieldMethods,
  FormErrorTypes,
  FormState,
  ValidationIssue,
} from '@tanstack/form-core'
import type { FunctionComponent } from 'react'
import type { CrossVersionReactNode } from '../reactTypes.public'
import type {
  ReactFormFieldProps,
  ReactFormSubscribeProps,
} from '../ReactForm/Components.public'
import type { ReadonlyAtom } from '@tanstack/react-store'

export interface FieldGroupFieldComponent<
  in out TFieldData,
  in out TFieldComponents extends Record<string, FunctionComponent<any>>,
> {
  <const TFieldName extends DeepKeys<TFieldData>>(
    props: ReactFormFieldProps<
      TFieldData,
      TFieldName,
      DeepValue<TFieldData, TFieldName>,
      FieldValidators<
        TFieldData,
        TFieldName,
        DeepValue<TFieldData, TFieldName>
      >,
      ValidationIssue,
      unknown,
      FormErrorTypes,
      TFieldComponents
    >,
  ): CrossVersionReactNode
}

export interface FieldGroupArrayFieldComponent<
  in out TFieldData,
  in out TFieldComponents extends Record<string, FunctionComponent<any>>,
> {
  <const TFieldName extends DeepKeysWhereValueIncludes<TFieldData, Array<any>>>(
    props: ReactFormFieldProps<
      TFieldData,
      TFieldName,
      DeepValue<TFieldData, TFieldName>,
      FieldValidators<
        TFieldData,
        TFieldName,
        DeepValue<TFieldData, TFieldName>
      >,
      ValidationIssue,
      unknown,
      FormErrorTypes,
      TFieldComponents
    >,
  ): CrossVersionReactNode
}

export type FieldGroupSubscribeProps<TSelected> = ReactFormSubscribeProps<
  unknown,
  FormErrorTypes,
  TSelected
>

export type FieldGroupSubscribeComponent = <TSelected>(
  props: FieldGroupSubscribeProps<TSelected>,
) => CrossVersionReactNode

export interface FieldGroupApi<
  in out TFieldData,
  in out TFieldComponents extends Record<string, FunctionComponent<any>> =
    Record<never, never>,
>
  extends FormApiFieldMethods<TFieldData>, FormApiArrayMethods<TFieldData> {
  atom: ReadonlyAtom<TFieldData>
  Field: FieldGroupFieldComponent<TFieldData, TFieldComponents>
  ArrayField: FieldGroupArrayFieldComponent<TFieldData, TFieldComponents>
  Subscribe: FieldGroupSubscribeComponent
}

export type AnyFieldGroupApi = FieldGroupApi<
  any,
  Record<string, FunctionComponent<any>>
>

export type FieldGroupFormState = FormState<unknown, FormErrorTypes>

// packages/solid-form/src/FieldGroup/FieldGroupApi.public.ts
import type {
  DeepKeys,
  DeepKeysWhereValueIncludes,
  DeepValue,
  FieldValidators,
  FormApiArrayMethods,
  FormApiFieldMethods,
  FormErrorTypes,
  FormState,
  ValidationIssue,
} from '@tanstack/form-core'
import type { Component, JSX } from 'solid-js'
import type {
  SolidFormFieldProps,
  SolidFormSubscribeProps,
} from '../Components.public'
import type { ReadonlyAtom } from '@tanstack/solid-store'

export interface FieldGroupFieldComponent<
  TFieldData,
  TFieldComponents extends Record<string, Component<any>>,
> {
  <const TFieldName extends DeepKeys<TFieldData>>(
    props: SolidFormFieldProps<
      TFieldData,
      TFieldName,
      DeepValue<TFieldData, TFieldName>,
      FieldValidators<
        TFieldData,
        TFieldName,
        DeepValue<TFieldData, TFieldName>
      >,
      ValidationIssue,
      unknown,
      FormErrorTypes,
      TFieldComponents
    >,
  ): JSX.Element
}

export interface FieldGroupArrayFieldComponent<
  TFieldData,
  TFieldComponents extends Record<string, Component<any>>,
> {
  <const TFieldName extends DeepKeysWhereValueIncludes<TFieldData, Array<any>>>(
    props: SolidFormFieldProps<
      TFieldData,
      TFieldName,
      DeepValue<TFieldData, TFieldName>,
      FieldValidators<
        TFieldData,
        TFieldName,
        DeepValue<TFieldData, TFieldName>
      >,
      ValidationIssue,
      unknown,
      FormErrorTypes,
      TFieldComponents
    >,
  ): JSX.Element
}

export type FieldGroupSubscribeProps<TSelected> = SolidFormSubscribeProps<
  unknown,
  FormErrorTypes,
  TSelected
>

export type FieldGroupSubscribeComponent = <TSelected>(
  props: FieldGroupSubscribeProps<TSelected>,
) => JSX.Element

export interface FieldGroupApi<
  TFieldData,
  TFieldComponents extends Record<string, Component<any>> = Record<
    never,
    never
  >,
>
  extends FormApiFieldMethods<TFieldData>, FormApiArrayMethods<TFieldData> {
  atom: ReadonlyAtom<TFieldData>
  Field: FieldGroupFieldComponent<TFieldData, TFieldComponents>
  ArrayField: FieldGroupArrayFieldComponent<TFieldData, TFieldComponents>
  Subscribe: FieldGroupSubscribeComponent
}

export type AnyFieldGroupApi = FieldGroupApi<
  any,
  Record<string, Component<any>>
>
export type FieldGroupFormState = FormState<unknown, FormErrorTypes>
