// examples/angular/query-integration/src/app.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  effect,
  inject,
} from '@angular/core'
import {
  QueryClient,
  injectMutation,
  injectQuery,
} from '@tanstack/angular-query-experimental'
import {
  TanStackField,
  injectForm,
  injectSelector,
} from '@tanstack/angular-form'
import { db, sleep } from './mock-db'
import type { StoredUser } from './mock-db'

const emptyUser: StoredUser = { firstName: '', lastName: '' }

@Component({
  selector: 'app-root',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [TanStackField],
  template: `
    <main>
      @if (userQuery.isPending()) {
        <p>Loading...</p>
      } @else if (userQuery.isError()) {
        <p role="alert">{{ userQuery.error().message }}</p>
      } @else {
        <h1>Query Integration Form Example</h1>
        <form (submit)="handleSubmit($event)">
          <ng-container
            [tanstackField]="form"
            name="firstName"
            [validators]="firstNameValidators"
            #firstName="field"
          >
            <label>
              <span>First Name</span>
              <input
                [name]="firstName.api.name"
                [value]="firstName.api.value"
                (blur)="firstName.api.handleBlur()"
                (input)="firstName.api.handleChange($any($event).target.value)"
                [attr.aria-invalid]="firstName.api.meta.isInvalid"
              />
              @for (error of firstName.api.errors; track error) {
                <small role="alert">{{ error.message }}</small>
              }
            </label>
          </ng-container>
          <ng-container
            [tanstackField]="form"
            name="lastName"
            #lastName="field"
          >
            <label>
              <span>Last Name</span>
              <input
                [name]="lastName.api.name"
                [value]="lastName.api.value"
                (blur)="lastName.api.handleBlur()"
                (input)="lastName.api.handleChange($any($event).target.value)"
              />
            </label>
          </ng-container>
          <div class="actions">
            <button type="submit" [disabled]="!canSubmit()">
              {{ isSubmitting() ? '...' : 'Submit' }}
            </button>
            <button type="button" (click)="form.reset()">Reset</button>
          </div>
        </form>
      }
    </main>
  `,
})
export class AppComponent {
  private queryClient = inject(QueryClient)
  userQuery = injectQuery(() => ({
    queryKey: ['user'],
    queryFn: () => db.getData(),
  }))
  saveUser = injectMutation(() => ({
    mutationFn: (value: StoredUser) => db.saveUser(value),
    onSuccess: () => this.queryClient.invalidateQueries({ queryKey: ['user'] }),
  }))

  firstNameValidators = [
    {
      run: ({ value }: { value: string }) =>
        !value
          ? 'A first name is required'
          : value.length < 3
            ? 'First name must be at least 3 characters'
            : undefined,
      triggers: ['change'] as const,
    },
    {
      run: async ({ value }: { value: string }) => {
        await sleep(1000)
        return value.includes('error')
          ? 'No "error" allowed in first name'
          : undefined
      },
      triggers: ['change'] as const,
      triggerDebounceMs: 500,
    },
  ]

  form = injectForm({
    defaultValues: emptyUser,
    errorVisibility: ({ fieldState }) => fieldState.meta.isTouched,
    onSubmit: async ({ formApi, value }) => {
      await this.saveUser.mutateAsync(value)
      formApi.reset(value)
    },
  })
  canSubmit = injectSelector(this.form, (state) => state.canSubmit)
  isSubmitting = injectSelector(this.form, (state) => state.isSubmitting)

  constructor() {
    effect(() => {
      const user = this.userQuery.data()
      if (user && !this.form.state.isTouched) this.form.reset(user)
    })
  }

  handleSubmit(event: SubmitEvent) {
    event.preventDefault()
    event.stopPropagation()
    this.form.handleSubmit()
  }
}

// examples/solid/query-integration/src/App.tsx
import { For, Show } from 'solid-js'
import {
  createMutation,
  createQuery,
  keepPreviousData,
} from '@tanstack/solid-query'
import { createForm } from '@tanstack/solid-form'
import { db, sleep } from './mock-db'
import type { Accessor } from 'solid-js'
import type { AnyFieldApi } from '@tanstack/solid-form'
import type { StoredUser } from './mock-db'

function FieldInfo(props: { field: Accessor<AnyFieldApi> }) {
  return (
    <>
      <Show when={props.field().meta.isInvalid}>
        <em role="alert">
          <For each={props.field().errors}>
            {(error, index) => (
              <>
                {index() > 0 ? ', ' : ''}
                {error.message}
              </>
            )}
          </For>
        </em>
      </Show>
      <Show when={props.field().meta.isValidating}>Validating...</Show>
    </>
  )
}

const emptyUser: StoredUser = {
  firstName: '',
  lastName: '',
}

export function App() {
  const userQuery = createQuery(() => ({
    queryKey: ['data'],
    queryFn: () => db.getData(),
    placeholderData: keepPreviousData,
  }))

  const saveUserMutation = createMutation(() => ({
    mutationFn: (value: StoredUser) => db.saveUser(value),
    onSuccess: async () => {
      await userQuery.refetch()
    },
  }))

  const form = createForm(() => ({
    defaultValues: userQuery.data ?? emptyUser,
    onSubmit: async ({ formApi, value }) => {
      await saveUserMutation.mutateAsync(value)
      formApi.reset(value)
    },
    errorVisibility: ({ fieldState }) => fieldState.meta.isTouched,
  }))

  return (
    <Show when={!userQuery.isPending} fallback={<p>Loading...</p>}>
      <div>
        <h1>Query Integration Form Example</h1>
        <form
          onSubmit={(event) => {
            event.preventDefault()
            event.stopPropagation()
            form.handleSubmit()
          }}
        >
          <form.Field
            name="firstName"
            validators={[
              {
                run: ({ value }) =>
                  !value
                    ? 'A first name is required'
                    : value.length < 3
                      ? 'First name must be at least 3 characters'
                      : undefined,
                triggers: ['change'],
              },
              {
                run: async ({ value }) => {
                  await sleep(1000)
                  return (
                    value.includes('error') &&
                    'No "error" allowed in first name'
                  )
                },
                triggers: ['change'],
                triggerDebounceMs: 500,
              },
            ]}
          >
            {(field) => (
              <div>
                <label for={field().name}>First Name:</label>
                <input
                  id={field().name}
                  name={field().name}
                  value={field().value}
                  onBlur={field().handleBlur}
                  onInput={(event) =>
                    field().handleChange(event.currentTarget.value)
                  }
                  aria-invalid={field().meta.isInvalid}
                />
                <FieldInfo field={field} />
              </div>
            )}
          </form.Field>
          <form.Field name="lastName">
            {(field) => (
              <div>
                <label for={field().name}>Last Name:</label>
                <input
                  id={field().name}
                  name={field().name}
                  value={field().value}
                  onBlur={field().handleBlur}
                  onInput={(event) =>
                    field().handleChange(event.currentTarget.value)
                  }
                  aria-invalid={field().meta.isInvalid}
                />
                <FieldInfo field={field} />
              </div>
            )}
          </form.Field>
          <form.Subscribe
            selector={(state) => [state.canSubmit, state.isSubmitting] as const}
          >
            {(state) => (
              <>
                <button type="submit" disabled={!state()[0] || state()[1]}>
                  {state()[1] ? '...' : 'Submit'}
                </button>
                <button
                  type="reset"
                  onClick={(event) => {
                    event.preventDefault()
                    form.reset()
                  }}
                >
                  Reset
                </button>
              </>
            )}
          </form.Subscribe>
        </form>
      </div>
    </Show>
  )
}
