// examples/svelte/basic-splitting-form/src/App.svelte
<script lang="ts">
  import { createForm } from '@tanstack/svelte-form'
  import FormSection from './FormSection.svelte'
  import FormSubmitButton from './FormSubmitButton.svelte'
  import StringField from './StringField.svelte'
  import { sharedFormOptions } from './sharedForm.js'
  import './index.css'

  const form = createForm(() => ({
    ...sharedFormOptions,
    onSubmit: ({ value }) => {
      console.log(value)
    },
  }))
</script>

<div>
  <h1>Split Form Example</h1>
  <form
    onsubmit={(event) => {
      event.preventDefault()
      event.stopPropagation()
      form.handleSubmit()
    }}
  >
    <form.Field name="firstName">
      {#snippet children(field)}
        <StringField {field} label="First Name" />
      {/snippet}
    </form.Field>
    <form.Field name="lastName">
      {#snippet children(field)}
        <StringField {field} label="Last Name" />
      {/snippet}
    </form.Field>
    <FormSection {form} />
    <FormSubmitButton {form} />
    <button
      type="reset"
      onclick={(event) => {
        event.preventDefault()
        form.reset()
      }}
    >
      Reset
    </button>
  </form>
</div>

// examples/angular/basic-splitting-form/src/app.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import {
  TanStackAppField,
  TanStackField,
  injectForm,
  injectSelector,
} from '@tanstack/angular-form'
import { FormSectionComponent } from './form-section.component'
import { StringFieldComponent } from './string-field.component'
import { SubmitButtonComponent } from './submit-button.component'
import { sharedFormOptions } from './shared-form'

@Component({
  selector: 'app-root',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    TanStackAppField,
    TanStackField,
    FormSectionComponent,
    StringFieldComponent,
    SubmitButtonComponent,
  ],
  template: `
    <main>
      <h1>Split Form Example</h1>
      <form (submit)="handleSubmit($event)">
        <app-string-field
          label="First Name"
          tanstack-app-field
          [tanstackField]="form"
          name="firstName"
        />
        <app-string-field
          label="Last Name"
          tanstack-app-field
          [tanstackField]="form"
          name="lastName"
        />
        <app-form-section [form]="form" />
        <div class="actions">
          <app-submit-button
            [canSubmit]="canSubmit"
            [isSubmitting]="isSubmitting"
          />
          <button type="button" (click)="form.reset()">Reset</button>
        </div>
      </form>
    </main>
  `,
})
export class AppComponent {
  form = injectForm({
    ...sharedFormOptions,
    onSubmit: ({ value }) => console.log(value),
  })
  canSubmit = injectSelector(this.form, (state) => state.canSubmit)
  isSubmitting = injectSelector(this.form, (state) => state.isSubmitting)

  handleSubmit(event: SubmitEvent) {
    event.preventDefault()
    event.stopPropagation()
    this.form.handleSubmit()
  }
}
