// examples/solid/basic-splitting-form/src/FieldError.tsx
import { For } from 'solid-js'
import type { Accessor } from 'solid-js'
import type { AnyFieldApi } from '@tanstack/solid-form'

export function FieldError(props: { field: Accessor<AnyFieldApi> }) {
  return (
    <small
      role={props.field().meta.isInvalid ? 'alert' : undefined}
      aria-live="polite"
    >
      <For each={props.field().errors}>
        {(error, index) => (
          <>
            {index() > 0 ? '\n' : ''}
            {error.message}
          </>
        )}
      </For>
    </small>
  )
}

// examples/react/field-groups/src/FieldError.tsx
import type { AnyFieldApi } from '@tanstack/react-form'

interface FieldInfoProps {
  field: AnyFieldApi
}

export function FieldError({ field }: FieldInfoProps) {
  return (
    <small role={field.meta.isInvalid ? 'alert' : undefined} aria-live="polite">
      {field.errors.map((e) => e.message).join('\n')}
    </small>
  )
}
