// examples/lit/field-groups/src/field-error.ts
import { html, nothing } from 'lit'
import type { AnyFieldApi } from '@tanstack/lit-form'

export function fieldError(field: AnyFieldApi) {
  return html`<small
    role=${field.meta.isInvalid ? 'alert' : nothing}
    aria-live="polite"
  >
    ${field.errors.map((error) => error.message).join(', ')}
  </small>`
}

// examples/react/field-groups/src/FieldError.tsx
import type { AnyFieldApi } from '@tanstack/react-form'

interface FieldInfoProps {
  field: AnyFieldApi
}

export function FieldError({ field }: FieldInfoProps) {
  return (
    <small role={field.meta.isInvalid ? 'alert' : undefined} aria-live="polite">
      {field.errors.map((e) => e.message).join('\n')}
    </small>
  )
}
