// examples/solid/field-groups/src/StringField.tsx
import { FieldError } from './FieldError'
import type { Accessor } from 'solid-js'
import type { FieldWithValue } from '@tanstack/solid-form'

interface StringFieldProps {
  field: Accessor<FieldWithValue<string>>
  label: string
}

export function StringField(props: StringFieldProps) {
  return (
    <label
      classList={{ validating: props.field().meta.isValidating }}
      style={{ display: 'block' }}
    >
      <span>{props.label}</span>
      <input
        name={props.field().name}
        value={props.field().value}
        onBlur={props.field().handleBlur}
        onInput={(event) =>
          props.field().handleChange(event.currentTarget.value)
        }
        aria-invalid={props.field().meta.isInvalid}
      />
      <br />
      <FieldError field={props.field} />
    </label>
  )
}

// examples/react/field-groups/src/StringField.tsx
import { FieldError } from './FieldError'
import type { FieldWithValue } from '@tanstack/react-form'

interface StringFieldProps {
  field: FieldWithValue<string>
  label: string
}

export function StringField(props: StringFieldProps) {
  const { field, label } = props

  return (
    <label
      className={field.meta.isValidating ? 'validating' : ''}
      style={{
        display: 'block',
      }}
    >
      <span>{label}</span>

      <input
        name={field.name}
        value={field.value}
        onBlur={field.handleBlur}
        onChange={(e) => field.handleChange(e.target.value)}
        aria-invalid={field.meta.isInvalid}
      />
      <br />
      <FieldError field={field} />
    </label>
  )
}
