// examples/vue/field-components/src/components/TextField.vue
<script setup lang="ts">
import { useStore } from '@tanstack/vue-form'
import { injectField } from '../compositions/form-providers'

const props = defineProps(['label'])

const field = injectField<string>()

const errors = useStore(field.store, (state) => state.meta.errors)
</script>

<template>
  <div>
    <label>
      <div>{{ props.label }}</div>
      <input
        :value="field.state.value"
        @input="field.handleChange(($event as any).target.value)"
      />
    </label>
    <div v-for="error in errors" :key="error" style="color: red">
      {{ error }}
    </div>
  </div>
</template>

// examples/angular/multi-step-wizard/src/app/text-field.component.ts
import { Component, input } from '@angular/core'
import { injectField } from '@tanstack/angular-form'

@Component({
  selector: 'app-text-field',
  standalone: true,
  template: `
    <div>
      <label>
        <div>{{ label() }}</div>
        <input
          [value]="field.api.state.value"
          (input)="field.api.handleChange($any($event).target.value)"
          (blur)="field.api.handleBlur()"
        />
      </label>
      @for (error of field.api.state.meta.errors; track $index) {
        <div style="color: red">
          {{ error.message }}
        </div>
      }
    </div>
  `,
})
export class TextFieldComponent {
  label = input.required<string>()
  field = injectField<string>()
}
