// examples/vue/simple/src/FieldInfo.vue
<script setup lang="ts">
import type { AnyFieldApi } from '@tanstack/vue-form'

defineProps<{ field: AnyFieldApi }>()
</script>

<template>
  <template v-if="field.meta.isTouched && field.meta.isInvalid">
    <em role="alert">
      {{ field.errors.map((error) => error.message).join(', ') }}
    </em>
  </template>
  <span v-if="field.meta.isValidating" aria-live="polite"> Validating... </span>
</template>

// examples/svelte/query-integration/src/FieldInfo.svelte
<script lang="ts">
  import type { AnyFieldApi } from '@tanstack/svelte-form'

  const { field }: { field: AnyFieldApi } = $props()
</script>

{#if field.meta.isInvalid}
  <em role="alert">
    {field.errors.map((error) => error.message).join(', ')}
  </em>
{/if}
{#if field.meta.isValidating}Validating...{/if}
