// examples/vue/field-components/src/components/TextField.vue
<script setup lang="ts">
import { useStore } from '@tanstack/vue-form'
import { injectField } from '../compositions/form-providers'

const props = defineProps(['label'])

const field = injectField<string>()

const errors = useStore(field.store, (state) => state.meta.errors)
</script>

<template>
  <div>
    <label>
      <div>{{ props.label }}</div>
      <input
        :value="field.state.value"
        @input="field.handleChange(($event as any).target.value)"
      />
    </label>
    <div v-for="error in errors" :key="error" style="color: red">
      {{ error }}
    </div>
  </div>
</template>

// examples/svelte/large-form/src/components/text-field.svelte
<script lang="ts">
  import { useFieldContext } from '../runes/form-context.js'

  const field = useFieldContext<string>()

  const { label }: { label: string } = $props()
</script>

<div>
  <label>
    <div>{label}</div>
    <input
      id={field.name}
      value={field.state.value}
      oninput={(e) => field.handleChange((e.target as HTMLInputElement).value)}
    />
  </label>
  {#each field.state.meta.errors as error}
    <div style="color: red;">{error}</div>
  {/each}
</div>
