// examples/solid/basic-splitting-form/src/StringField.tsx
import { FieldError } from './FieldError'
import type { Accessor } from 'solid-js'
import type { FieldWithValue } from '@tanstack/solid-form'

interface StringFieldProps {
  field: Accessor<FieldWithValue<string>>
  label: string
}

export function StringField(props: StringFieldProps) {
  return (
    <label classList={{ validating: props.field().meta.isValidating }}>
      <span>{props.label}</span>
      <input
        name={props.field().name}
        value={props.field().value}
        onBlur={props.field().handleBlur}
        onInput={(event) =>
          props.field().handleChange(event.currentTarget.value)
        }
        aria-invalid={props.field().meta.isInvalid}
      />
      <FieldError field={props.field} />
    </label>
  )
}

// examples/svelte/field-groups/src/StringField.svelte
<script lang="ts">
  import type { FieldWithValue } from '@tanstack/svelte-form'
  import FieldError from './FieldError.svelte'

  interface Props {
    field: FieldWithValue<string>
    label: string
  }

  const { field, label }: Props = $props()
</script>

<label class:validating={field.meta.isValidating}>
  <span>{label}</span>
  <input
    name={field.name}
    value={field.value}
    onblur={field.handleBlur}
    oninput={(event) => field.handleChange(event.currentTarget.value)}
    aria-invalid={field.meta.isInvalid}
  />
  <FieldError {field} />
</label>
