// examples/svelte/multi-step-wizard/src/features/wizard/step2-subform.svelte
<script lang="ts">
  import { getFormType } from '../../runes/form.js'
  import { step2Schema, wizardFormOpts } from './shared-form.js'

  const formType = getFormType({ ...wizardFormOpts })

  const {
    form,
    step,
    setStep,
  }: {
    form: typeof formType
    step: number
    setStep: (step: number) => void
  } = $props()
</script>

<form.FormGroup
  name="step2"
  validators={{
    onDynamic: step2Schema,
  }}
  onGroupSubmit={({ value: _value }) => {
    form.handleSubmit()
  }}
>
  {#snippet children(formGroup)}
    <form
      onsubmit={(e) => {
        e.preventDefault()
        e.stopPropagation()
        formGroup.handleSubmit()
      }}
    >
      <form.AppField name="step2.name">
        {#snippet children(field)}
          <field.TextField label="Step 2 Name" />
        {/snippet}
      </form.AppField>

      <button type="button" onclick={() => setStep(step - 1)}>Back</button>
      <form.AppForm>
        {#snippet children()}
          <form.SubscribeButton label="Submit" />
        {/snippet}
      </form.AppForm>
    </form>
  {/snippet}
</form.FormGroup>

// examples/preact/multi-step-wizard/src/features/wizard/step2-subform.tsx
import { step2Schema, stepValidator } from './shared-form'
import type { wizardFormOpts } from './shared-form'
import type { PreactFormType } from '@tanstack/preact-form'

type WizardForm = PreactFormType<typeof wizardFormOpts>

interface Step2FormProps {
  form: WizardForm
  step: number
  setStep: (step: number) => void
}

export function Step2Form({ form, step, setStep }: Step2FormProps) {
  return (
    <form.FormGroup
      name="step2"
      validators={[stepValidator(step2Schema)]}
      onSubmit={() => {
        form.handleSubmit()
      }}
    >
      {(formGroup) => (
        <form
          onSubmit={(e) => {
            e.preventDefault()
            e.stopPropagation()
            formGroup.handleSubmit()
          }}
        >
          <formGroup.Field name="name">
            {(field) => <field.TextField label="Step 2 Name" />}
          </formGroup.Field>

          <button type="button" onClick={() => setStep(step - 1)}>
            Back
          </button>
          <form.SubscribeButton label="Submit" />
        </form>
      )}
    </form.FormGroup>
  )
}
