// examples/react/basic-splitting-form/src/FormSubmitButton.tsx
import type { AnyReactFormApi } from '@tanstack/react-form'

interface FormSubmitButtonProps {
  form: AnyReactFormApi
}

export function FormSubmitButton(props: FormSubmitButtonProps) {
  const { form } = props
  return (
    <form.Subscribe selector={(state) => [state.canSubmit, state.isSubmitting]}>
      {([canSubmit, isSubmitting]) => (
        <button type="submit" disabled={!canSubmit || isSubmitting}>
          {isSubmitting ? '...' : 'Submit'}
        </button>
      )}
    </form.Subscribe>
  )
}

// examples/svelte/basic-splitting-form/src/FormSubmitButton.svelte
<script lang="ts">
  import type { AnySvelteFormApi } from '@tanstack/svelte-form'

  const { form }: { form: AnySvelteFormApi } = $props()
</script>

<form.Subscribe
  selector={(state) => [state.canSubmit, state.isSubmitting] as const}
>
  {#snippet children([canSubmit, isSubmitting])}
    <button type="submit" disabled={!canSubmit || isSubmitting}>
      {isSubmitting ? '...' : 'Submit'}
    </button>
  {/snippet}
</form.Subscribe>
