// examples/lit/field-groups/src/index.ts
import { LitElement, html } from 'lit'
import { customElement } from 'lit/decorators.js'
import { TanStackFormController } from '@tanstack/lit-form'
import { DateRangeField } from './date-range'
import { LowerBoundField, UpperBoundField } from './field-bounds'
import './styles.css'

@customElement('tanstack-field-groups')
export class TanStackFieldGroups extends LitElement {
  private pricingForm = new TanStackFormController(this, {
    defaultValues: { minPrice: '', maxPrice: '' },
  })

  private ageForm = new TanStackFormController(this, {
    defaultValues: { minAge: '', maxAge: '' },
  })

  private dateForm = new TanStackFormController(this, {
    defaultValues: {
      dateRanges: [
        { id: 'A', start: '2026-07-01', end: '2026-07-05' },
        { id: 'B', start: '2026-08-10', end: '2026-08-15' },
      ],
    },
  })

  protected createRenderRoot() {
    return this
  }

  render() {
    return html`
      <h1>Reusable Field Group Example</h1>
      <section>
        <h2>Price Filter Form</h2>
        ${LowerBoundField({
          form: this.pricingForm,
          fields: { value: 'minPrice' },
          label: 'Lowest Price',
        })}
        ${UpperBoundField({
          form: this.pricingForm,
          fields: { value: 'maxPrice', lowerBound: 'minPrice' },
          label: 'Highest Price',
        })}
      </section>
      <section>
        <h2>Age Range Form</h2>
        ${LowerBoundField({
          form: this.ageForm,
          fields: { value: 'minAge' },
          label: 'Lowest Age',
        })}
        ${UpperBoundField({
          form: this.ageForm,
          fields: { value: 'maxAge', lowerBound: 'minAge' },
          label: 'Highest Age',
        })}
      </section>
      <section>
        <h2>Swappable Date Ranges</h2>
        <button
          type="button"
          @click=${() => this.dateForm.api.swapFieldValues('dateRanges', 0, 1)}
        >
          Swap date ranges
        </button>
        ${this.dateForm.arrayField({ name: 'dateRanges' }, (array) =>
          array.value.map((range, index) =>
            DateRangeField({
              form: this.dateForm,
              fields: {
                start: `dateRanges[${index}].start`,
                end: `dateRanges[${index}].end`,
              },
              label: `Range ${range.id}`,
            }),
          ),
        )}
      </section>
    `
  }
}

// examples/solid/field-groups/src/index.tsx
import { For } from 'solid-js'
import { render } from 'solid-js/web'
import { createForm } from '@tanstack/solid-form'
import { DateRangeField } from './fieldGroups/dateRange'
import { LowerBoundField, UpperBoundField } from './fieldGroups/fieldBounds'
import './index.css'

function PricingFilterForm() {
  const form = createForm(() => ({
    defaultValues: {
      minPrice: '',
      maxPrice: '',
    },
  }))

  return (
    <>
      <LowerBoundField
        label="Lowest Price"
        form={form}
        fields={{ value: 'minPrice' }}
      />
      <UpperBoundField
        label="Highest Price"
        form={form}
        fields={{
          value: 'maxPrice',
          lowerBound: 'minPrice',
        }}
      />
    </>
  )
}

function AgeRangeForm() {
  const form = createForm(() => ({
    defaultValues: {
      minAge: '',
      maxAge: '',
    },
  }))

  return (
    <>
      <LowerBoundField
        label="Lowest Age"
        form={form}
        fields={{ value: 'minAge' }}
      />
      <UpperBoundField
        label="Highest Age"
        form={form}
        fields={{
          value: 'maxAge',
          lowerBound: 'minAge',
        }}
      />
    </>
  )
}

function SwappableDateRangesForm() {
  const form = createForm(() => ({
    defaultValues: {
      dateRanges: [
        { id: 'A', start: '2026-07-01', end: '2026-07-05' },
        { id: 'B', start: '2026-08-10', end: '2026-08-15' },
      ],
    },
  }))

  return (
    <>
      <button
        type="button"
        onClick={() => form.swapFieldValues('dateRanges', 0, 1)}
      >
        Swap date ranges
      </button>
      <form.ArrayField name="dateRanges">
        {(array) => (
          <For each={array().value}>
            {(range, index) => (
              <DateRangeField
                label={`Range ${range.id}`}
                form={form}
                fields={{
                  start: `dateRanges[${index()}].start`,
                  end: `dateRanges[${index()}].end`,
                }}
              />
            )}
          </For>
        )}
      </form.ArrayField>
    </>
  )
}

function App() {
  return (
    <div>
      <h1>Field Group Example</h1>
      <section>
        <h2>Price Filter Form</h2>
        <PricingFilterForm />
      </section>
      <section>
        <h2>Age Range Form</h2>
        <AgeRangeForm />
      </section>
      <section>
        <h2>Swappable Date Ranges Form</h2>
        <SwappableDateRangesForm />
      </section>
    </div>
  )
}

render(() => <App />, document.getElementById('root')!)
