// examples/react/large-form/src/components/text-fields.tsx
import { useStore } from '@tanstack/react-form'
import { useFieldContext } from '../hooks/form-context.tsx'

export default function TextField({ label }: { label: string }) {
  const field = useFieldContext<string>()

  const errors = useStore(field.store, (state) => state.meta.errors)

  return (
    <div>
      <label>
        <div>{label}</div>
        <input
          value={field.state.value}
          onChange={(e) => field.handleChange(e.target.value)}
        />
      </label>
      {errors.map((error: string) => (
        <div key={error} style={{ color: 'red' }}>
          {error}
        </div>
      ))}
    </div>
  )
}

// examples/solid/multi-step-wizard/src/components/text-fields.tsx
import { For } from 'solid-js'
import { useStore } from '@tanstack/solid-form'
import { useFieldContext } from '../hooks/form-context.tsx'

export function TextField(props: { label: string }) {
  const field = useFieldContext<string>()

  const errors = useStore(field().store, (state) => state.meta.errors)

  return (
    <div>
      <label>
        <div>{props.label}</div>
        <input
          value={field().state.value}
          onChange={(e) => field().handleChange(e.target.value)}
        />
      </label>
      <For each={errors()}>
        {(error) => <div style={{ color: 'red' }}>{error}</div>}
      </For>
    </div>
  )
}
