// packages/react-form/src/Field.tsx
import * as React from 'react'
import {
  functionalUpdate,
  type DeepKeys,
  type DeepValue,
  type FieldApi,
  type FieldOptions,
  type FormApi,
} from '@tanstack/form-core'
import { useField } from './useField'

//

export type FieldComponent<TFormData> = <TField extends DeepKeys<TFormData>>({
  children,
  ...fieldOptions
}: {
  children: (fieldApi: FieldApi<DeepValue<TFormData, TField>, TFormData>) => any
  name: TField
} & Omit<FieldOptions<DeepValue<TFormData, TField>, TFormData>, 'name'>) => any

export function createFieldComponent<TFormData>(formApi: FormApi<TFormData>) {
  const ConnectedField: FieldComponent<TFormData> = (props) => (
    <Field {...(props as any)} form={formApi} />
  )
  return ConnectedField
}

export function Field<TData, TFormData>({
  children,
  ...fieldOptions
}: {
  children: (fieldApi: FieldApi<TData, TFormData>) => any
} & FieldOptions<TData, TFormData>) {
  const fieldApi = useField(fieldOptions as any)
  return functionalUpdate(children, fieldApi as any)
}

// packages/vue-form/src/Field.vue
<template>
  <slot v-bind="fieldApi" />
</template>

<script setup lang="ts" generic="TData, TFormData">
import { useField, UseFieldOptions } from './useField'
import { provideFormContext } from './formContext'

const fieldOptions = defineProps<UseFieldOptions<TData, TFormData>>()

const fieldApi = useField(fieldOptions)

provideFormContext({
  formApi: fieldApi.form,
  parentFieldName: fieldApi.name,
})
</script>
