// examples/preact/basic-splitting-form/src/FormSubmitButton.tsx
import type { AnyPreactFormApi } from '@tanstack/preact-form'

interface FormSubmitButtonProps {
  form: AnyPreactFormApi
}

export function FormSubmitButton(props: FormSubmitButtonProps) {
  const { form } = props
  return (
    <form.Subscribe selector={(state) => [state.canSubmit, state.isSubmitting]}>
      {([canSubmit, isSubmitting]) => (
        <button type="submit" disabled={!canSubmit || isSubmitting}>
          {isSubmitting ? '...' : 'Submit'}
        </button>
      )}
    </form.Subscribe>
  )
}

// examples/lit/basic-splitting-form/src/form-submit-button.ts
import { html } from 'lit'
import type { AnyLitFormApi } from '@tanstack/lit-form'

export function formSubmitButton(form: AnyLitFormApi) {
  return form.subscribe(
    (state) => [state.canSubmit, state.isSubmitting] as const,
    ([canSubmit, isSubmitting]) => html`
      <button type="submit" ?disabled=${!canSubmit || isSubmitting}>
        ${isSubmitting ? '...' : 'Submit'}
      </button>
    `,
  )
}
