// examples/svelte/large-form/src/features/people/address-fields.svelte
<script lang="ts">
  import { getFormType } from '../../runes/form.js'
  import { peopleFormOpts } from './shared-form.js'

  const formType = getFormType({ ...peopleFormOpts })

  const { form }: { form: typeof formType } = $props()
</script>

<div>
  <h2>Address</h2>
  <form.AppField name="address.line1">
    {#snippet children(field)}
      <field.TextField label="Address Line 1" />
    {/snippet}
  </form.AppField>
  <form.AppField name="address.line2">
    {#snippet children(field)}
      <field.TextField label="Address Line 2" />
    {/snippet}
  </form.AppField>
  <form.AppField name="address.city">
    {#snippet children(field)}
      <field.TextField label="City" />
    {/snippet}
  </form.AppField>
  <form.AppField name="address.state">
    {#snippet children(field)}
      <field.TextField label="State" />
    {/snippet}
  </form.AppField>
  <form.AppField name="address.zip">
    {#snippet children(field)}
      <field.TextField label="ZIP Code" />
    {/snippet}
  </form.AppField>
</div>

// examples/vue/large-form/src/features/people/AddressFields.vue
<script setup lang="ts">
import { getFormType } from '../../compositions/form.ts'
import { peopleFormOpts } from './shared-form.ts'
import { computed } from 'vue'

const formType = getFormType({ ...peopleFormOpts })
const props = defineProps<{ form: typeof formType }>()
const form = computed(() => props.form)
</script>

<template>
  <div>
    <h2>Address</h2>
    <form.AppField name="address.line1" v-slot="{ field }">
      <field.TextField label="Address Line 1" />
    </form.AppField>
    <form.AppField name="address.line2" v-slot="{ field }">
      <field.TextField label="Address Line 2" />
    </form.AppField>
    <form.AppField name="address.city" v-slot="{ field }">
      <field.TextField label="City" />
    </form.AppField>
    <form.AppField name="address.state" v-slot="{ field }">
      <field.TextField label="State" />
    </form.AppField>
    <form.AppField name="address.zip" v-slot="{ field }">
      <field.TextField label="ZIP Code" />
    </form.AppField>
  </div>
</template>
