// examples/svelte/large-form/src/features/people/emergency-contact.svelte
<script lang="ts">
  import { getFormType } from '../../runes/form.js'
  import { peopleFormOpts } from './shared-form.js'

  const formType = getFormType({ ...peopleFormOpts })

  const { form }: { form: typeof formType } = $props()
</script>

<form.AppField name="emergencyContact.fullName">
  {#snippet children(field)}
    <field.TextField label="Full Name" />
  {/snippet}
</form.AppField>
<form.AppField name="emergencyContact.phone">
  {#snippet children(field)}
    <field.TextField label="Phone" />
  {/snippet}
</form.AppField>

// examples/vue/large-form/src/features/people/EmergencyContact.vue
<script setup lang="ts">
import { getFormType } from '../../compositions/form.ts'
import { peopleFormOpts } from './shared-form.ts'
import { computed } from 'vue'

const formType = getFormType({ ...peopleFormOpts })
const props = defineProps<{ form: typeof formType }>()
const form = computed(() => props.form)
</script>

<template>
  <form.AppField name="emergencyContact.fullName" v-slot="{ field }">
    <field.TextField label="Full Name" />
  </form.AppField>
  <form.AppField name="emergencyContact.phone" v-slot="{ field }">
    <field.TextField label="Phone" />
  </form.AppField>
</template>
