// examples/svelte/large-form/src/features/people/AddressFields.svelte
<script lang="ts">
  import type { SvelteFormType } from '@tanstack/svelte-form'
  import type { peopleFormOpts } from './shared-form.js'

  const { form }: { form: SvelteFormType<typeof peopleFormOpts> } = $props()
</script>

<section>
  <h2>Address</h2>
  <form.Field name="address.line1">
    {#snippet children(field)}<field.TextField label="Address Line 1" />{/snippet}
  </form.Field>
  <form.Field name="address.line2">
    {#snippet children(field)}<field.TextField label="Address Line 2" />{/snippet}
  </form.Field>
  <form.Field name="address.city">
    {#snippet children(field)}<field.TextField label="City" />{/snippet}
  </form.Field>
  <form.Field name="address.state">
    {#snippet children(field)}<field.TextField label="State" />{/snippet}
  </form.Field>
  <form.Field name="address.zip">
    {#snippet children(field)}<field.TextField label="ZIP Code" />{/snippet}
  </form.Field>
</section>

// examples/solid/large-form/src/features/people/address-fields.tsx
import type { SolidFormType } from '@tanstack/solid-form'
import type { peopleFormOpts } from './shared-form'

export function AddressFields(props: {
  form: SolidFormType<typeof peopleFormOpts>
}) {
  return (
    <div>
      <h2>Address</h2>
      <props.form.Field name="address.line1">
        {(field) => <field.TextField label="Address Line 1" />}
      </props.form.Field>
      <props.form.Field name="address.line2">
        {(field) => <field.TextField label="Address Line 2" />}
      </props.form.Field>
      <props.form.Field name="address.city">
        {(field) => <field.TextField label="City" />}
      </props.form.Field>
      <props.form.Field name="address.state">
        {(field) => <field.TextField label="State" />}
      </props.form.Field>
      <props.form.Field name="address.zip">
        {(field) => <field.TextField label="ZIP Code" />}
      </props.form.Field>
    </div>
  )
}
