// examples/svelte/large-form/src/features/people/emergency-contact.svelte
<script lang="ts">
  import type { createAppForm } from '../../runes/form.js'
  import { peopleFormOpts } from './shared-form.js'

  type AppForm = ReturnType<typeof createAppForm<typeof peopleFormOpts.defaultValues>>

  const { form }: { form: AppForm } = $props()
</script>

<form.AppField name="emergencyContact.fullName">
  {#snippet children(field)}
    <field.TextField label="Full Name" />
  {/snippet}
</form.AppField>
<form.AppField name="emergencyContact.phone">
  {#snippet children(field)}
    <field.TextField label="Phone" />
  {/snippet}
</form.AppField>

// examples/solid/large-form/src/features/people/emergency-contact.tsx
import { withFieldGroup } from '../../hooks/form'

export const FieldGroupEmergencyContact = withFieldGroup({
  defaultValues: {
    phone: '',
    fullName: '',
  },
  render: function Render({ group }) {
    return (
      <>
        <group.AppField
          name="fullName"
          children={(field) => <field.TextField label="Full Name" />}
        />
        <group.AppField
          name="phone"
          children={(field) => <field.TextField label="Phone" />}
        />
      </>
    )
  },
})
