// examples/lit/basic-splitting-form/src/form-submit-button.ts
import { html } from 'lit'
import type { AnyLitFormApi } from '@tanstack/lit-form'

export function formSubmitButton(form: AnyLitFormApi) {
  return form.subscribe(
    (state) => [state.canSubmit, state.isSubmitting] as const,
    ([canSubmit, isSubmitting]) => html`
      <button type="submit" ?disabled=${!canSubmit || isSubmitting}>
        ${isSubmitting ? '...' : 'Submit'}
      </button>
    `,
  )
}

// examples/solid/basic-splitting-form/src/FormSubmitButton.tsx
import type { AnySolidFormApi } from '@tanstack/solid-form'

export function FormSubmitButton(props: { form: AnySolidFormApi }) {
  return (
    <props.form.Subscribe
      selector={(state) => [state.canSubmit, state.isSubmitting] as const}
    >
      {(state) => (
        <button type="submit" disabled={!state()[0] || state()[1]}>
          {state()[1] ? '...' : 'Submit'}
        </button>
      )}
    </props.form.Subscribe>
  )
}
