// examples/svelte/basic-splitting-form/src/FormSection.svelte
<script lang="ts">
  import type { SvelteFormType } from '@tanstack/svelte-form'
  import StringField from './StringField.svelte'
  import type { sharedFormOptions } from './sharedForm.js'

  const { form }: { form: SvelteFormType<typeof sharedFormOptions> } = $props()
</script>

<form.Field name="address.street">
  {#snippet children(field)}
    <StringField {field} label="Street" />
  {/snippet}
</form.Field>
<form.Field name="address.country">
  {#snippet children(field)}
    <StringField {field} label="Country" />
  {/snippet}
</form.Field>

// examples/solid/basic-splitting-form/src/FormSection.tsx
import { StringField } from './StringField'
import type { SolidFormType } from '@tanstack/solid-form'
import type { sharedFormOptions } from './sharedForm'

interface FormSectionProps {
  form: SolidFormType<typeof sharedFormOptions>
}

export function FormSection(props: FormSectionProps) {
  return (
    <>
      <props.form.Field name="address.street">
        {(field) => <StringField field={field} label="Street" />}
      </props.form.Field>
      <props.form.Field name="address.country">
        {(field) => <StringField field={field} label="Country" />}
      </props.form.Field>
    </>
  )
}
