// examples/lit/basic-splitting-form/src/index.ts
import { LitElement, html } from 'lit'
import { customElement } from 'lit/decorators.js'
import { TanStackFormController } from '@tanstack/lit-form'
import { formSection } from './form-section'
import { formSubmitButton } from './form-submit-button'
import { sharedFormOptions } from './shared-form'
import { stringField } from './string-field'
import './styles.css'

@customElement('tanstack-split-form')
export class TanStackSplitForm extends LitElement {
  private form = new TanStackFormController(this, {
    ...sharedFormOptions,
    onSubmit: ({ value }) => {
      console.log(value)
    },
  })

  protected createRenderRoot() {
    return this
  }

  render() {
    return html`
      <h1>Split Form Example</h1>
      <form
        @submit=${(event: SubmitEvent) => {
          event.preventDefault()
          event.stopPropagation()
          void this.form.api.handleSubmit()
        }}
      >
        ${this.form.field({ name: 'firstName' }, (field) =>
          stringField(field, 'First Name'),
        )}
        ${this.form.field({ name: 'lastName' }, (field) =>
          stringField(field, 'Last Name'),
        )}
        ${formSection(this.form)} ${formSubmitButton(this.form)}
        <button
          type="reset"
          @click=${(event: Event) => {
            event.preventDefault()
            this.form.api.reset()
          }}
        >
          Reset
        </button>
      </form>
    `
  }
}

// examples/solid/basic-splitting-form/src/index.tsx
import { render } from 'solid-js/web'
import { createForm } from '@tanstack/solid-form'
import { FormSection } from './FormSection'
import { FormSubmitButton } from './FormSubmitButton'
import { StringField } from './StringField'
import { sharedFormOptions } from './sharedForm'
import './index.css'

function App() {
  const form = createForm(() => ({
    ...sharedFormOptions,
    onSubmit: ({ value }) => {
      console.log(value)
    },
  }))

  return (
    <div>
      <h1>Form Splitting Example</h1>
      <form
        onSubmit={(event) => {
          event.preventDefault()
          event.stopPropagation()
          form.handleSubmit()
        }}
      >
        <form.Field name="firstName">
          {(field) => <StringField field={field} label="First Name" />}
        </form.Field>
        <form.Field name="lastName">
          {(field) => <StringField field={field} label="Last Name" />}
        </form.Field>

        <FormSection form={form} />

        <FormSubmitButton form={form} />
        <button
          type="reset"
          onClick={(event) => {
            event.preventDefault()
            form.reset()
          }}
        >
          Reset
        </button>
      </form>
    </div>
  )
}

render(() => <App />, document.getElementById('root')!)
