// examples/react/multi-step-wizard/src/features/wizard/step2-subform.tsx
import { withForm } from '../../hooks/form'
import { step2Schema, wizardFormOpts } from './shared-form'

export const Step2Form = withForm({
  ...wizardFormOpts,
  props: {
    step: 1,
    setStep: (_step: number) => {},
  },
  render: function Render({ form, step, setStep }) {
    return (
      <form.FormGroup
        name="step2"
        validators={{
          onDynamic: step2Schema
        }}
        onGroupSubmit={({ value: _value }) => {
          form.handleSubmit()
        }}
      >
        {(formGroup) => (
          <form
            onSubmit={(e) => {
              e.preventDefault()
              e.stopPropagation()
              formGroup.handleSubmit()
            }}
          >
            <form.AppField name="step2.name">
              {(field) => <field.TextField label="Step 2 Name" />}
            </form.AppField>

            <button onClick={() => setStep(step - 1)}>Back</button>
            <form.AppForm>
              <form.SubscribeButton label="Submit" />
            </form.AppForm>
          </form>
        )}
      </form.FormGroup>
    )
  },
})

// examples/svelte/multi-step-wizard/src/features/wizard/step2-subform.svelte
<script lang="ts">
  import { getFormType } from '../../runes/form.js'
  import { step2Schema, wizardFormOpts } from './shared-form.js'

  const formType = getFormType({ ...wizardFormOpts })

  const {
    form,
    step,
    setStep,
  }: {
    form: typeof formType
    step: number
    setStep: (step: number) => void
  } = $props()
</script>

<form.FormGroup
  name="step2"
  validators={{
    onDynamic: step2Schema,
  }}
  onGroupSubmit={({ value: _value }) => {
    form.handleSubmit()
  }}
>
  {#snippet children(formGroup)}
    <form
      onsubmit={(e) => {
        e.preventDefault()
        e.stopPropagation()
        formGroup.handleSubmit()
      }}
    >
      <form.AppField name="step2.name">
        {#snippet children(field)}
          <field.TextField label="Step 2 Name" />
        {/snippet}
      </form.AppField>

      <button type="button" onclick={() => setStep(step - 1)}>Back</button>
      <form.AppForm>
        {#snippet children()}
          <form.SubscribeButton label="Submit" />
        {/snippet}
      </form.AppForm>
    </form>
  {/snippet}
</form.FormGroup>
