// examples/vue/field-components/src/App.vue
<script setup lang="ts">
import { formOptions } from '@tanstack/vue-form'
import { useAppForm } from './compositions/form'

const peopleFormOpts = formOptions({
  defaultValues: {
    fullName: '',
    email: '',
    phone: '',
    emergencyContact: {
      fullName: '',
      phone: '',
    },
  },
})

const form = useAppForm({
  ...peopleFormOpts,
  validators: {
    onChange: ({ value }) => {
      const errors = {
        fields: {},
      } as {
        fields: Record<string, string>
      }
      if (!value.fullName) {
        errors.fields.fullName = 'Full name is required'
      }
      if (!value.phone) {
        errors.fields.phone = 'Phone is required'
      }
      if (!value.emergencyContact.fullName) {
        errors.fields['emergencyContact.fullName'] =
          'Emergency contact full name is required'
      }
      if (!value.emergencyContact.phone) {
        errors.fields['emergencyContact.phone'] =
          'Emergency contact phone is required'
      }

      return errors
    },
  },
  onSubmit: ({ value }) => {
    alert(JSON.stringify(value, null, 2))
  },
})
</script>

<template>
  <form @submit.prevent.stop="form.handleSubmit()">
    <h1>Personal Information</h1>
    <form.AppField name="fullName" v-slot="{ field }">
      <field.TextField label="Full Name" />
    </form.AppField>
    <form.AppField name="email" v-slot="{ field }">
      <field.TextField label="Email" />
    </form.AppField>
    <form.AppField name="phone" v-slot="{ field }">
      <field.TextField label="Phone" />
    </form.AppField>
    <h2>Emergency Contact</h2>
    <form.AppField name="emergencyContact.fullName" v-slot="{ field }">
      <field.TextField label="Full Name" />
    </form.AppField>
    <form.AppField name="emergencyContact.phone" v-slot="{ field }">
      <field.TextField label="Phone" />
    </form.AppField>
    <form.AppForm>
      <form.SubscribeButton label="Submit" />
    </form.AppForm>
  </form>
</template>

// examples/angular/large-form/src/app.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import {
  TanStackAppField,
  TanStackField,
  injectForm,
  injectSelector,
} from '@tanstack/angular-form'
import { AddressFieldsComponent } from './address-fields.component'
import { EmergencyContactComponent } from './emergency-contact.component'
import { peopleFormOptions } from './shared-form'
import { TextFieldComponent } from './text-field.component'

@Component({
  selector: 'app-root',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    AddressFieldsComponent,
    EmergencyContactComponent,
    TanStackAppField,
    TanStackField,
    TextFieldComponent,
  ],
  template: `
    <main>
      <form (submit)="handleSubmit($event)">
        <h1>Personal Information</h1>
        @for (field of personalFields; track field.name) {
          <app-text-field
            [label]="field.label"
            tanstack-app-field
            [tanstackField]="form"
            [name]="field.name"
          />
        }
        <app-address-fields [form]="form" />
        <app-emergency-contact
          [form]="form"
          [fields]="{
            fullName: 'emergencyContact.fullName',
            phone: 'emergencyContact.phone',
          }"
        />
        <button type="submit" [disabled]="isSubmitting()">
          {{ isSubmitting() ? '...' : 'Submit' }}
        </button>
      </form>
    </main>
  `,
})
export class AppComponent {
  personalFields = [
    { name: 'fullName' as const, label: 'Full Name' },
    { name: 'email' as const, label: 'Email' },
    { name: 'phone' as const, label: 'Phone' },
  ]
  form = injectForm({
    ...peopleFormOptions,
    onSubmit: ({ value }) => alert(JSON.stringify(value, null, 2)),
  })
  isSubmitting = injectSelector(this.form, (state) => state.isSubmitting)

  handleSubmit(event: SubmitEvent) {
    event.preventDefault()
    this.form.handleSubmit()
  }
}
