// examples/angular/simple/src/app.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import {
  TanStackField,
  injectForm,
  injectSelector,
} from '@tanstack/angular-form'

@Component({
  selector: 'app-root',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [TanStackField],
  template: `
    <main>
      <h1>Simple Form Example</h1>
      <form (submit)="handleSubmit($event)">
        <ng-container
          [tanstackField]="form"
          name="firstName"
          [validators]="firstNameValidators"
          #firstName="field"
        >
          <label [class.validating]="firstName.api.meta.isValidating">
            <span>First Name</span>
            <input
              [name]="firstName.api.name"
              [value]="firstName.api.value"
              (blur)="firstName.api.handleBlur()"
              (input)="firstName.api.handleChange($any($event).target.value)"
              [attr.aria-invalid]="firstName.api.meta.isInvalid"
            />
            @if (firstName.api.meta.isTouched && firstName.api.meta.isInvalid) {
              @for (error of firstName.api.errors; track error) {
                <small role="alert">{{ error.message }}</small>
              }
            }
          </label>
        </ng-container>

        <ng-container [tanstackField]="form" name="lastName" #lastName="field">
          <label>
            <span>Last Name</span>
            <input
              [name]="lastName.api.name"
              [value]="lastName.api.value"
              (blur)="lastName.api.handleBlur()"
              (input)="lastName.api.handleChange($any($event).target.value)"
            />
          </label>
        </ng-container>

        <div class="actions">
          <button type="submit" [disabled]="!canSubmit()">
            {{ isSubmitting() ? '...' : 'Submit' }}
          </button>
          <button type="button" (click)="form.reset()">Reset</button>
        </div>
      </form>
    </main>
  `,
})
export class AppComponent {
  firstNameValidators = [
    {
      run: ({ value }: { value: string }) =>
        !value
          ? 'A first name is required'
          : value.length < 3
            ? 'First name must be at least 3 characters'
            : undefined,
      triggers: ['change'] as const,
    },
    {
      run: async ({ value }: { value: string }) => {
        await new Promise((resolve) => setTimeout(resolve, 1000))
        return value.includes('error')
          ? 'No "error" allowed in first name'
          : undefined
      },
      triggers: ['change'] as const,
      triggerDebounceMs: 500,
    },
  ]

  form = injectForm({
    defaultValues: { firstName: '', lastName: '' },
    onSubmit: async ({ value }) => console.log(value),
  })
  canSubmit = injectSelector(this.form, (state) => state.canSubmit)
  isSubmitting = injectSelector(this.form, (state) => state.isSubmitting)

  handleSubmit(event: SubmitEvent) {
    event.preventDefault()
    event.stopPropagation()
    this.form.handleSubmit()
  }
}

// examples/svelte/basic/src/App.svelte
<script lang="ts">
  import { createForm } from '@tanstack/svelte-form'
  import FieldError from './FieldError.svelte'
  import './index.css'

  const form = createForm(() => ({
    defaultValues: {
      firstName: '',
      lastName: '',
    },
    onSubmit: ({ value, createValidationError }) => {
      console.log(value)
      return createValidationError({
        fields: {
          firstName: 'Name already exists',
          lastName: 'Name already exists',
        },
      })
    },
  }))
</script>

<div>
  <h1>Basic Form Example</h1>
  <form
    onsubmit={(event) => {
      event.preventDefault()
      event.stopPropagation()
      form.handleSubmit()
    }}
  >
    <form.Field
      name="firstName"
      validators={[
        {
          run: ({ value }) => {
            if (value.length === 0) return 'A first name is required'
            if (value.length < 3) return 'First name is too short'
          },
          triggers: ['change', 'blur'],
          triggerDebounceMs: 300,
        },
        {
          run: async ({ value }) => {
            await new Promise((resolve) => setTimeout(resolve, 1000))
            return (
              value.toLowerCase().includes('error') &&
              'No "error" allowed in first name'
            )
          },
          triggers: ['change'],
          bailIfInvalid: true,
        },
      ]}
    >
      {#snippet children(field)}
        <label class:validating={field.meta.isValidating}>
          <span>First Name</span>
          <input
            name={field.name}
            value={field.value}
            onblur={field.handleBlur}
            oninput={(event) => field.handleChange(event.currentTarget.value)}
            aria-invalid={field.meta.isInvalid}
          />
          <FieldError {field} />
        </label>
      {/snippet}
    </form.Field>
    <form.Field name="lastName">
      {#snippet children(field)}
        <label class:validating={field.meta.isValidating}>
          <span>Last Name</span>
          <input
            name={field.name}
            value={field.value}
            onblur={field.handleBlur}
            oninput={(event) => field.handleChange(event.currentTarget.value)}
            aria-invalid={field.meta.isInvalid}
          />
          <FieldError {field} />
        </label>
      {/snippet}
    </form.Field>
    <form.Subscribe
      selector={(state) => [state.canSubmit, state.isSubmitting] as const}
    >
      {#snippet children([canSubmit, isSubmitting])}
        <button type="submit" disabled={!canSubmit || isSubmitting}>
          {isSubmitting ? '...' : 'Submit'}
        </button>
      {/snippet}
    </form.Subscribe>
    <button
      type="reset"
      onclick={(event) => {
        event.preventDefault()
        form.reset()
      }}
    >
      Reset
    </button>
  </form>
</div>
