// examples/lit/field-groups/src/date-range.ts
import { html } from 'lit'
import { getFieldGroupHelpers } from '@tanstack/lit-form'
import { stringField } from './string-field'

const { defineFields, helper, withFields } = getFieldGroupHelpers()

const dateRangeFields = defineFields({
  start: helper.strict<string>(),
  end: helper.strict<string>(),
})

function dateRangeField(props: {
  fields: typeof dateRangeFields
  label: string
}) {
  return html`
    <fieldset>
      <legend>${props.label}</legend>
      ${props.fields.field({ name: 'start' }, (field) =>
        stringField(field, 'Start date', 'date'),
      )}
      ${props.fields.field(
        {
          name: 'end',
          validators: [
            {
              triggers: [
                {
                  trigger: 'change',
                  when: ({ value }) => Boolean(value),
                },
              ],
              watchFields: ['start'],
              run: ({ value }) => {
                const start = props.fields.getFieldValue('start')
                if (start && value < start) {
                  return 'End date must be after the start date'
                }
              },
            },
          ],
        },
        (field) => stringField(field, 'End date', 'date'),
      )}
    </fieldset>
  `
}

export const DateRangeField = withFields(
  dateRangeFields,
  dateRangeField,
  'fields',
)

// examples/react/field-groups/src/fieldGroups/dateRange.tsx
import { getFieldGroupHelpers } from '@tanstack/react-form'
import { FieldError } from '../FieldError'
import type { FieldWithValue } from '@tanstack/react-form'

const { defineFields, helper, withFields } = getFieldGroupHelpers()

const dateRangeFields = defineFields({
  start: helper.strict<string>(),
  end: helper.strict<string>(),
})

interface DateRangeFieldProps {
  fields: typeof dateRangeFields
  label: string
}

function DateRangeFieldComponent(props: DateRangeFieldProps) {
  const { fields, label } = props

  return (
    <fieldset>
      <legend>{label}</legend>

      <fields.Field name="start">
        {(field) => <DateField field={field} label="Start date" />}
      </fields.Field>

      <fields.Field
        name="end"
        validators={[
          {
            triggers: [
              {
                trigger: 'change',
                when: ({ value }) =>
                  Boolean(value && fields.getFieldValue('start')),
              },
            ],
            watchFields: ['start'],
            run: ({ value }) => {
              const start = fields.getFieldValue('start')

              if (value < start) {
                return 'End date must be after the start date'
              }
            },
          },
        ]}
      >
        {(field) => <DateField field={field} label="End date" />}
      </fields.Field>
    </fieldset>
  )
}

export const DateRangeField = withFields(
  dateRangeFields,
  DateRangeFieldComponent,
  'fields',
)

interface DateFieldProps {
  field: FieldWithValue<string>
  label: string
}

function DateField(props: DateFieldProps) {
  const { field, label } = props

  return (
    <label
      className={field.meta.isValidating ? 'validating' : ''}
      style={{
        display: 'block',
      }}
    >
      <span>{label}</span>
      <input
        name={field.name}
        type="date"
        value={field.value}
        onBlur={field.handleBlur}
        onChange={(e) => field.handleChange(e.target.value)}
        aria-invalid={field.meta.isInvalid}
      />
      <br />
      <FieldError field={field} />
    </label>
  )
}
