// examples/angular/field-groups/src/date-range.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core'
import { TanStackField } from '@tanstack/angular-form'
import type { AnyAngularFormApi } from '@tanstack/angular-form'

@Component({
  selector: 'app-date-range',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [TanStackField],
  template: `
    <fieldset>
      <legend>{{ label() }}</legend>
      <ng-container
        [tanstackField]="form()"
        [name]="fields().start"
        #start="field"
      >
        <label>
          <span>Start date</span>
          <input
            type="date"
            [name]="start.api.name"
            [value]="start.api.value"
            (blur)="start.api.handleBlur()"
            (input)="start.api.handleChange($any($event).target.value)"
          />
        </label>
      </ng-container>
      <ng-container
        [tanstackField]="form()"
        [name]="fields().end"
        [validators]="endValidators()"
        #end="field"
      >
        <label>
          <span>End date</span>
          <input
            type="date"
            [name]="end.api.name"
            [value]="end.api.value"
            (blur)="end.api.handleBlur()"
            (input)="end.api.handleChange($any($event).target.value)"
            [attr.aria-invalid]="end.api.meta.isInvalid"
          />
          @for (error of end.api.errors; track error) {
            <small role="alert">{{ error.message }}</small>
          }
        </label>
      </ng-container>
    </fieldset>
  `,
})
export class DateRangeComponent {
  form = input.required<AnyAngularFormApi>()
  label = input.required<string>()
  fields = input.required<{ start: string; end: string }>()
  endValidators = computed(() => [
    {
      triggers: ['change'] as const,
      watchFields: [this.fields().start],
      run: ({ value }: { value: string }) => {
        const start = this.form().getFieldValue(this.fields().start)
        return value && start && value < start
          ? 'End date must be after the start date'
          : undefined
      },
    },
  ])
}

// examples/react/field-groups/src/fieldGroups/dateRange.tsx
import { getFieldGroupHelpers } from '@tanstack/react-form'
import { FieldError } from '../FieldError'
import type { FieldWithValue } from '@tanstack/react-form'

const { defineFields, helper, withFields } = getFieldGroupHelpers()

const dateRangeFields = defineFields({
  start: helper.strict<string>(),
  end: helper.strict<string>(),
})

interface DateRangeFieldProps {
  fields: typeof dateRangeFields
  label: string
}

function DateRangeFieldComponent(props: DateRangeFieldProps) {
  const { fields, label } = props

  return (
    <fieldset>
      <legend>{label}</legend>

      <fields.Field name="start">
        {(field) => <DateField field={field} label="Start date" />}
      </fields.Field>

      <fields.Field
        name="end"
        validators={[
          {
            triggers: [
              {
                trigger: 'change',
                when: ({ value }) =>
                  Boolean(value && fields.getFieldValue('start')),
              },
            ],
            watchFields: ['start'],
            run: ({ value }) => {
              const start = fields.getFieldValue('start')

              if (value < start) {
                return 'End date must be after the start date'
              }
            },
          },
        ]}
      >
        {(field) => <DateField field={field} label="End date" />}
      </fields.Field>
    </fieldset>
  )
}

export const DateRangeField = withFields(
  dateRangeFields,
  DateRangeFieldComponent,
  'fields',
)

interface DateFieldProps {
  field: FieldWithValue<string>
  label: string
}

function DateField(props: DateFieldProps) {
  const { field, label } = props

  return (
    <label
      className={field.meta.isValidating ? 'validating' : ''}
      style={{
        display: 'block',
      }}
    >
      <span>{label}</span>
      <input
        name={field.name}
        type="date"
        value={field.value}
        onBlur={field.handleBlur}
        onChange={(e) => field.handleChange(e.target.value)}
        aria-invalid={field.meta.isInvalid}
      />
      <br />
      <FieldError field={field} />
    </label>
  )
}
