// examples/vue/large-form/src/features/people/EmergencyContactFields.vue
<script setup lang="ts">
import type { emergencyContactFields } from './emergency-contact.ts'

const { fields } = defineProps<{
  fields: typeof emergencyContactFields
}>()
</script>

<template>
  <fields.Field name="fullName" v-slot="{ field }">
    <field.TextField label="Full Name" />
  </fields.Field>
  <fields.Field name="phone" v-slot="{ field }">
    <field.TextField label="Phone" />
  </fields.Field>
</template>

// examples/svelte/large-form/src/features/people/EmergencyContactFields.svelte
<script lang="ts">
  import type { emergencyContactFields } from './emergency-contact.js'

  export interface Props {
    fields: typeof emergencyContactFields
  }

  const { fields }: Props = $props()
</script>

<fields.Field name="fullName">
  {#snippet children(field)}<field.TextField label="Full Name" />{/snippet}
</fields.Field>
<fields.Field name="phone">
  {#snippet children(field)}<field.TextField label="Phone" />{/snippet}
</fields.Field>
