// examples/preact/large-form/src/features/people/emergency-contact.tsx
import { defineAppFieldGroup } from '../../hooks/form'

const fieldGroup = defineAppFieldGroup(({ strict }) => ({
  fullName: strict<string>(),
  phone: strict<string>(),
}))

function EmergencyContactFields({
  fields,
}: {
  fields: typeof fieldGroup.fields
}) {
  return (
    <>
      <fields.Field
        name="fullName"
        children={(field) => <field.TextField label="Full Name" />}
      />
      <fields.Field
        name="phone"
        children={(field) => <field.TextField label="Phone" />}
      />
    </>
  )
}

export const FieldGroupEmergencyContact = fieldGroup.bindComponent(
  EmergencyContactFields,
  'fields',
)

// examples/svelte/large-form/src/features/people/emergency-contact.svelte
<script lang="ts">
  import { getFormType } from '../../runes/form.js'
  import { peopleFormOpts } from './shared-form.js'

  const formType = getFormType({ ...peopleFormOpts })

  const { form }: { form: typeof formType } = $props()
</script>

<form.AppField name="emergencyContact.fullName">
  {#snippet children(field)}
    <field.TextField label="Full Name" />
  {/snippet}
</form.AppField>
<form.AppField name="emergencyContact.phone">
  {#snippet children(field)}
    <field.TextField label="Phone" />
  {/snippet}
</form.AppField>
