// examples/solid/large-form/src/features/people/page.tsx
import { useAppForm } from '../../hooks/form'
import { AddressFields } from './address-fields'
import { FieldGroupEmergencyContact } from './emergency-contact'
import { peopleFormOpts } from './shared-form'

export function PeoplePage() {
  const form = useAppForm(() => ({
    ...peopleFormOpts,
    onSubmit: ({ value }) => {
      alert(JSON.stringify(value, null, 2))
    },
  }))

  return (
    <form
      onSubmit={(event) => {
        event.preventDefault()
        form.handleSubmit()
      }}
    >
      <h1>Personal Information</h1>
      <form.Field name="fullName">
        {(field) => <field.TextField label="Full Name" />}
      </form.Field>
      <form.Field name="email">
        {(field) => <field.TextField label="Email" />}
      </form.Field>
      <form.Field name="phone">
        {(field) => <field.TextField label="Phone" />}
      </form.Field>

      <AddressFields form={form} />

      <h2>Emergency Contact</h2>
      <FieldGroupEmergencyContact
        form={form}
        fields={{
          fullName: 'emergencyContact.fullName',
          phone: 'emergencyContact.phone',
        }}
      />

      <form.AppForm>
        <form.SubscribeButton label="Submit" />
      </form.AppForm>
    </form>
  )
}

// examples/svelte/large-form/src/features/people/Page.svelte
<script lang="ts">
  import { useAppForm } from '../../hooks/form.js'
  import AddressFields from './AddressFields.svelte'
  import { FieldGroupEmergencyContact } from './emergency-contact.js'
  import { peopleFormOpts } from './shared-form.js'

  const form = useAppForm(() => ({
    ...peopleFormOpts,
    onSubmit: ({ value }) => {
      alert(JSON.stringify(value, null, 2))
    },
  }))
</script>

<form
  onsubmit={(event) => {
    event.preventDefault()
    form.handleSubmit()
  }}
>
  <h1>Personal Information</h1>
  <form.Field name="fullName">
    {#snippet children(field)}<field.TextField label="Full Name" />{/snippet}
  </form.Field>
  <form.Field name="email">
    {#snippet children(field)}<field.TextField label="Email" />{/snippet}
  </form.Field>
  <form.Field name="phone">
    {#snippet children(field)}<field.TextField label="Phone" />{/snippet}
  </form.Field>
  <AddressFields {form} />
  <h2>Emergency Contact</h2>
  <FieldGroupEmergencyContact
    {form}
    fields={{
      fullName: 'emergencyContact.fullName',
      phone: 'emergencyContact.phone',
    }}
  />
  <form.AppForm>
    <form.SubscribeButton label="Submit" />
  </form.AppForm>
</form>
