// examples/react/large-form/src/features/people/page.tsx
import { useAppForm } from '../../hooks/form.tsx'
import { AddressFields } from './address-fields.tsx'
import { FieldGroupEmergencyContact } from './emergency-contact.tsx'
import { peopleFormOpts } from './shared-form.tsx'

export const PeoplePage = () => {
  const form = useAppForm({
    ...peopleFormOpts,
    onSubmit: ({ value }) => {
      alert(JSON.stringify(value, null, 2))
    },
  })

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault()
        form.handleSubmit()
      }}
    >
      <h1>Personal Information</h1>
      <form.AppField
        name="fullName"
        children={(field) => <field.TextField label="Full Name" />}
      />
      <form.AppField
        name="email"
        children={(field) => <field.TextField label="Email" />}
      />
      <form.AppField
        name="phone"
        children={(field) => <field.TextField label="Phone" />}
      />
      <AddressFields form={form} />
      <h2>Emergency Contact</h2>
      <FieldGroupEmergencyContact form={form} fields="emergencyContact" />

      <form.AppForm>
        <form.SubscribeButton label="Submit" />
      </form.AppForm>
    </form>
  )
}

// examples/svelte/large-form/src/features/people/Page.svelte
<script lang="ts">
  import { useAppForm } from '../../hooks/form.js'
  import AddressFields from './AddressFields.svelte'
  import { FieldGroupEmergencyContact } from './emergency-contact.js'
  import { peopleFormOpts } from './shared-form.js'

  const form = useAppForm(() => ({
    ...peopleFormOpts,
    onSubmit: ({ value }) => {
      alert(JSON.stringify(value, null, 2))
    },
  }))
</script>

<form
  onsubmit={(event) => {
    event.preventDefault()
    form.handleSubmit()
  }}
>
  <h1>Personal Information</h1>
  <form.Field name="fullName">
    {#snippet children(field)}<field.TextField label="Full Name" />{/snippet}
  </form.Field>
  <form.Field name="email">
    {#snippet children(field)}<field.TextField label="Email" />{/snippet}
  </form.Field>
  <form.Field name="phone">
    {#snippet children(field)}<field.TextField label="Phone" />{/snippet}
  </form.Field>
  <AddressFields {form} />
  <h2>Emergency Contact</h2>
  <FieldGroupEmergencyContact
    {form}
    fields={{
      fullName: 'emergencyContact.fullName',
      phone: 'emergencyContact.phone',
    }}
  />
  <form.AppForm>
    <form.SubscribeButton label="Submit" />
  </form.AppForm>
</form>
