// packages/angular-form/src/form-group.ts
import {
  ChangeDetectorRef,
  Directive,
  effect,
  inject,
  input,
} from '@angular/core'
import { InternalFormGroupApi } from '@tanstack/form-core/internals'
import type {
  DeepKeys,
  DeepValue,
  FormGroupOptions,
  FormGroupValidators,
  FormValidators,
  ToFormErrorTypes,
} from '@tanstack/form-core'
import type { InternalFormApi } from '@tanstack/form-core/internals'

@Directive({
  selector: '[tanstackFormGroup]',
  standalone: true,
  exportAs: 'formGroup',
})
export class TanStackFormGroup<
  TFormData,
  const TGroupName extends DeepKeys<TFormData>,
  TGroupValue extends DeepValue<TFormData, TGroupName>,
  const TGroupValidators extends FormGroupValidators<TGroupValue>,
  const TFormValidators extends FormValidators<TFormData>,
  TSubmitReturn,
> {
  tanstackFormGroup =
    input.required<InternalFormApi<TFormData, TFormValidators, TSubmitReturn>>()
  name = input.required<TGroupName>()
  validators = input<NoInfer<TGroupValidators>>()
  onSubmit =
    input<
      FormGroupOptions<
        TFormData,
        TGroupName,
        TGroupValue,
        TGroupValidators,
        ToFormErrorTypes<TFormValidators, TSubmitReturn>
      >['onSubmit']
    >()
  onSubmitInvalid =
    input<
      FormGroupOptions<
        TFormData,
        TGroupName,
        TGroupValue,
        TGroupValidators,
        ToFormErrorTypes<TFormValidators, TSubmitReturn>
      >['onSubmitInvalid']
    >()

  private readonly changeDetector = inject(ChangeDetectorRef)
  private group: InternalFormGroupApi<
    TFormData,
    TGroupName,
    TGroupValue,
    TGroupValidators,
    ToFormErrorTypes<TFormValidators, TSubmitReturn>
  > | null = null

  private getOptions() {
    return {
      form: this.tanstackFormGroup(),
      name: this.name(),
      validators: this.validators(),
      onSubmit: this.onSubmit(),
      onSubmitInvalid: this.onSubmitInvalid(),
    }
  }

  get api() {
    if (!this.group) {
      this.group = new InternalFormGroupApi(this.getOptions() as never)
    }
    return this.group
  }

  constructor() {
    effect(() => this.api.update(this.getOptions() as never))

    effect((onCleanup) => {
      const group = this.api
      group.mount()
      onCleanup(() => group._cleanup())
    })

    effect((onCleanup) => {
      const subscription = this.api.atom.subscribe(() => {
        this.changeDetector.markForCheck()
      })
      onCleanup(() => subscription.unsubscribe())
    })
  }
}

// packages/svelte-form/src/FormGroup.svelte
<script module lang="ts">
  import { InternalFormGroupApi } from '@tanstack/form-core/internals'
  import { useSelector } from '@tanstack/svelte-store'
  import { withComponentProps } from './utils.lib.js'
  import type {
    FormErrorTypes,
    FormGroupApi,
    FormGroupOptions,
    FormGroupValidators,
    ToFormGroupErrorTypes,
  } from '@tanstack/form-core'
  import type { AnyInternalFormApi } from '@tanstack/form-core/internals'

  export function createFormGroup<
    TFormData,
    TGroupName,
    TGroupValue,
    const TGroupValidators extends FormGroupValidators<TGroupValue>,
    TFormErrorTypes extends FormErrorTypes,
  >(
    options: () => FormGroupOptions<
      TFormData,
      TGroupName,
      TGroupValue,
      TGroupValidators,
      TFormErrorTypes
    >,
  ): FormGroupApi<
    TFormData,
    TGroupName,
    TGroupValue,
    ToFormGroupErrorTypes<TGroupValidators>,
    TFormErrorTypes
  > {
    const group = new InternalFormGroupApi(options() as never)

    $effect.pre(() => {
      group.update(options() as never)
    })
    $effect(() => {
      group.mount()
      return () => group._cleanup()
    })

    const state = useSelector(group.atom)

    return new Proxy({} as typeof group, {
      get(target, property) {
        if (Reflect.has(target, property)) return Reflect.get(target, property)
        if (property === 'state') return state.current
        if (property === 'value') return state.current.values
        const value = Reflect.get(group, property, group)
        return typeof value === 'function' ? value.bind(group) : value
      },
    }) as never
  }

  export function attachGroupComponents(
    group: any,
    form: AnyInternalFormApi & Record<string, any>,
  ) {
    group.Field = (internals: any, props: any) =>
      form.Field(internals, group._getFormFieldOptions(props))
    group.ArrayField = (internals: any, props: any) =>
      form.ArrayField(internals, group._getFormFieldOptions(props))
    group.Subscribe = (internals: any, props: any) =>
      form._Subscribe(
        internals,
        withComponentProps(props, { source: group.atom }),
      )
    return group
  }
</script>

<script lang="ts">
  import { untrack, type Snippet } from 'svelte'

  interface Props {
    form: AnyInternalFormApi & Record<string, any>
    children: Snippet<[any]>
    name: string
    validators?: any
    onSubmit?: any
    onSubmitInvalid?: any
  }

  let { children, form, ...groupOptions }: Props = $props()
  const initialForm = untrack(() => form)
  const groupApi = attachGroupComponents(
    createFormGroup(() => ({ ...groupOptions, form: initialForm }) as never),
    initialForm,
  )
</script>

{@render children(groupApi)}
